/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pboproject;

import javax.swing.JOptionPane;

/**
 *
 * @author Devi
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tblhelp = new javax.swing.JButton();
        tbladmin = new javax.swing.JButton();
        tblclient = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblhelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pboproject/ui/helpbutton.png"))); // NOI18N
        tblhelp.setContentAreaFilled(false);
        getContentPane().add(tblhelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 280, -1, -1));

        tbladmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pboproject/ui/adminbutton.png"))); // NOI18N
        tbladmin.setContentAreaFilled(false);
        tbladmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbladminMouseClicked(evt);
            }
        });
        tbladmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbladminActionPerformed(evt);
            }
        });
        getContentPane().add(tbladmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, -1, -1));

        tblclient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pboproject/ui/clientbutton.png"))); // NOI18N
        tblclient.setContentAreaFilled(false);
        tblclient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblclientActionPerformed(evt);
            }
        });
        getContentPane().add(tblclient, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pboproject/ui/bg.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(1366, 738));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setSize(new java.awt.Dimension(1382, 776));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tblclientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblclientActionPerformed
        new PopUpClient().setVisible(true);
    }//GEN-LAST:event_tblclientActionPerformed

    private void tbladminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbladminMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbladminMouseClicked

    private void tbladminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbladminActionPerformed
        new PopUpAdmin().setVisible(true);
    }//GEN-LAST:event_tbladminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton tbladmin;
    private javax.swing.JButton tblclient;
    private javax.swing.JButton tblhelp;
    // End of variables declaration//GEN-END:variables
}
